### ISSUE TITLE
Mobile - Header: Hamburger menu is missing

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#111]
## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6#/screens/282815784)

## Expected Behaviour
Tapping on hamburger menu should surface the option to sign in or sign up.

## Note
All icons are from [Material Icons](material.io/icons/)

## Work Needed
- [ ] Works on mobile
- [ ] Works on desktop
- [ ] Wrote some tests

**Comment by rosexw** [comment]
I have left this as a pull request, but is not complete yet. I don't think I'll have anymore time the rest of this week, due to other commitments - please help/assign to someone else.

- Tried adding a hamburger menu icon from Material IO.
- The icon is added in as a button, but no lists displays yet.
- I tried adding the menu list items into the Menu.

Needed to do still:

- add menu lists to menu
- make list items clickable or links?
- only have the hamburger menu show up in mobile view
